### ISSUE TITLE
Unable to convert Brick.ttl to DTDL

### ISSUE THREAD

**Issue by mkolarek** [Azure-Samples/RdfToDtdlConverter#2]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Running the RdfToDtdlConverter application on MacOS BigSur 11.1 attempting to convert the Brick ontology v1.1.0 downloaded from https://brickschema.org/schema/1.1/Brick.ttl

`dotnet bin/Debug/netcoreapp3.1/RdfToDtdlConverter.dll --rdf-file ~/Downloads/Brick.ttl --dtdl-file Brick.json --dtmi-prefix com:example --model-version 2`

### Any log messages given by the failure
`...
Error 823:
dtmi:com:example:Sensor;2's property 'extends' has value '' that is not a DTMI or a DTDL term. Replace the value of property 'extends, with a valid DTMI or a term defined by DTDL -- see https://github.com/Azure/opendigitaltwins-dtdl/tree/master/DTDL.
Primary ID: dtmi:com:example:Sensor;2
Secondary ID: 
Property: extends`

### Expected/desired behavior
Converting the Brick ontology turtle file to a valid DTDL as documented in the official documentation https://docs.microsoft.com/en-gb/azure/digital-twins/how-to-integrate-models#convert-existing-models-to-dtdl

### OS and Version?
macOS 11.1 Big Sur, version 201702

### Mention any other details that might be useful
Looking at the official documentation it seems this should be possible - if not, could you please point me to a version of RdfToDtdlConverter that is capable of converting Brick?

**Comment by gs9824** [comment]
I have similar issues while trying to convert the following :

https://forge.etsi.org/rep/SAREF/saref-core/blob/38b3304d58a1c3464b10da3f9d5747c51a51fdbb/ontology/saref.ttl

Although conversion works, loading in Azure digital twins fails for two reasons 

1.  the "extends" properties contains null. This leads to the same error message as described above : property 'extends' has value '' that is not a DTMI or a DTDL term.
2.  A comment with more than 512 characters is not supported

This is the DTDL as generated by the converter :

  {
    "@id": "dtmi:com:saref:Device;2",
    "@type": "Interface",
    "contents": [],
    "@context": "dtmi:dtdl:context;2",
    "extends": [
      null,
      null
    ],
    "displayName": "Device^^http://www.w3.org/2001/XMLSchema#string",
    "comment": "A tangible object designed to accomplish a particular task in households, common public buildings or offices. In order to accomplish this task, the device performs one or more functions. For example, a washing machine is designed to wash (task) and to accomplish this task it performs a start and stop function. Devices can be structured in categories (subclasses) that reflect the different domain in which a device is used, e.g., smart appliances domain (subclass FunctionRelated) vs. building domain (subclass BuildingRelated) vs. smart grid domain (subclass EnergyRelated). New categories can be defined,if needed, to reflect other differences, for example different points of view, such as the point of view of the device's user vs. the point of view of the device's manufacturer. We propose a list of devices that are relevant for the purpose of SAREF, but this list can be extended.^^http://www.w3.org/2001/XMLSchema#string"
  },

**Comment by georghildebrand** [comment]
@khilscher , is there any update if and when this would be fixed?

I just investigated a little and afaik this boils down to this [issue](https://github.com/Azure/opendigitaltwins-dtdl/issues/104)

In DTDL the maximum # of interfaces that can be extended is "2" so in Brick i count 770 of these classes (max to the level 9). [Notebook](https://gist.github.com/georghildebrand/23552c9bce51095e93e723b84cb502c7)

A side question here would be why are only two extendable interfaces possible

**Comment by khilscher** [comment]
@georghildebrand The constraint of extending from a max of two interfaces is from the DTDL v2 specification. Suggest raising an issue on the DTDL v2 specification repo if you would like to see this constraint relaxed.

**Comment by khilscher** [comment]
@mkolarek 

The Brick.ttl file converts cleanly now, except for:

```
DTDL written to: Brick.json
Validating DTDL...
No DtmiResolver provided to resolve requisite reference(s): dtmi:com:example:FeatureOfInterest;1 dtmi:com:example:Concept;1 dtmi:com:example:ObservableProperty;1
Validation complete! 
```

This is because these are owl:Imports, which is not implemented in this code sample (happy to accept a contribution if someone wants to implement this). The workaround is to simply open the Brick.json file and manually create these three interfaces.
